spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true

security:
  ignored: /health

flyway:
  url: ${JDBC_DATABASE_URL}
  locations: classpath:/db/migration
  baselineOnMigrate: true
  checkLocation: true

loxapi.security.jwt:
  tokenExpirationTime: 15 # Number of minutes
  refreshTokenExpTime: 60 # Minutes
  tokenIssuer: http://localhost:8080 # TODO: make env var
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus # TODO: Change value and set via env var
