spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true

security:
  ignored: /health

flyway:
  url: ${JDBC_DATABASE_URL}
  locations: classpath:/db/migration
  baselineOnMigrate: true
  checkLocation: true
