spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: testfail
#    url: ${JDBC_DATABASE_URL}
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:test;MODE=PostgreSQL
#    url: jdbc:postgresql://localhost:5432/my_db
#    username: root
#    password: root
#    driver-class-name: org.postgresql.Driver
