CREATE TABLE APP_USER (
  ID SERIAL PRIMARY KEY,
  USERNAME TEXT NOT NULL,
  PASSWORD TEXT NOT NULL
);

CREATE TABLE USER_ROLE (
  APP_USER_ID INTEGER NOT NULL,
  ROLE TEXT NOT NULL
);

INSERT INTO APP_USER(USERNAME, PASSWORD) VALUES ('moemoe','$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y'); -- password is 'password' but BCrypt'ed
INSERT INTO USER_ROLE(APP_USER_ID, ROLE) VALUES (1, 'ADMIN');
