

INSERT INTO APP_USER(email, first_name, last_name, username, gender, photo_url, event_name, password, profile) VALUES
  ('moe.jay@gmail.com', 'Moe', 'Jay', 'mjay', 'MALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('stacy.mile@gmail.com', 'Stacy', 'mile', 'smile', 'FEMALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('kelly.j.smit@trashymail.com', 'Kelly', 'Smit', 'ksmit', 'FEMALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('jeremy.f.wilson@mailinator.com', 'Jeremy', 'Wilson', 'jwilson', 'MALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('george.t.jones@spambob.com', 'George', 'Jones', 'gjones', 'MALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('gertrude.w.conner@trashymail.com', 'Gertrude', 'Conner', 'gconner', 'FEMALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('david.k.engler@spambob.com', 'David', 'Engler', 'dengler', 'MALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('tracy.m.guidry@mailinator.com', 'Tracy', 'Guidry', 'tguidry', 'FEMALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('kaye.f.sherwood@pookmail.com', 'Kaye', 'Sherwood', 'ksherwood', 'FEMALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('carol.p.house@pookmail.com', 'Carol', 'House', 'chouse', 'FEMALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('irma.r.mccormack@pookmail.com', 'Irma', 'Mccormack', 'imccormack', 'MALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('emma.r.shafer@spambob.com', 'Emma', 'Shafer', 'eshafer', 'FEMALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('charles.e.cleghorn@trashymail.com', 'Charles', 'Cleghorn', 'ccleghorn', 'MALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('florence.c.simpkins@spambob.com', 'Florence', 'Simpkins', 'fsimpkins', 'FEMALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('jason.b.nelson@trashymail.com', 'Jason', 'Nelson', 'jnelson', 'MALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('robt.h.cox@mailinator.com', 'Robt', 'Cox', 'rcox', 'MALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('lauren.l.mchugh@trashymail.com', 'Lauren', 'Mchugh', 'lmchugh', 'FEMALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('christina.c.barber@dodgit.com', 'Christina', 'Barber', 'cbarber', 'FEMALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('claude.m.lafayette@dodgit.com', 'Claude', 'Lafayette', 'clafayette', 'FEMALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('william.m.chase@dodgit.com', 'William', 'Chase', 'wchase', 'MALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('mireya.j.bruton@mailinator.com', 'Mireya', 'Bruton', 'mbruton', 'FEMALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('patsy.f.wozniak@dodgit.com', 'Patsy', 'Wozniak', 'pwozniak', 'FEMALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('maurice.a.nagata@mailinator.com', 'Maurice', 'Nagata', 'mnagata', 'FEMALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('charles.p.dews@dodgit.com', 'Charles', 'Dews', 'cdews', 'MALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('elizabeth.b.oliver@spambob.com', 'Elizabeth', 'Oliver', 'eoliver', 'FEMALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('jason.l.parks@pookmail.com', 'Jason', 'Parks', 'jparks', 'MALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}'),
  ('donna.m.childers@spambob.com', 'Donna', 'Childers', 'dchilders', 'FEMALE', 'https://postimg.org/image/rylpae5bj/', 'TEST1', '$2a$10$wplTezGx9cliSRkW2b6cfuJgck6OeAQuQ4apsNsNaz.tbSDwY6Z9y', '{"Q1": "Nisi debitis excepturi quae eum. Ipsa illo itaque sed commodi reiciendis repellendus suscipit.", "Q2": "Natus laborum fuga temporibus nobis. Excepturi assumenda id mollitia maxime laudantium. Voluptate maxime odio sed commodi.", "Q3": "Totam nam ratione esse impedit nemo. Non similique impedit ex odio. Dolorum quibusdam facilis fugiat temporibus voluptatum provident enim doloribus. Nobis iste ipsum harum temporibus ullam."}');
--------------------------

INSERT INTO USER_ROLE(APP_USER_ID, ROLE) VALUES
  (1, 'ADMIN'),
  (1, 'ADMIN'),
  (3, 'PARTICIPANT'),
  (4, 'PARTICIPANT'),
  (5, 'PARTICIPANT'),
  (6, 'PARTICIPANT'),
  (7, 'PARTICIPANT'),
  (8, 'PARTICIPANT'),
  (9, 'PARTICIPANT'),
  (10, 'PARTICIPANT'),
  (11, 'PARTICIPANT'),
  (12, 'PARTICIPANT'),
  (13, 'PARTICIPANT'),
  (14, 'PARTICIPANT'),
  (15, 'PARTICIPANT'),
  (16, 'PARTICIPANT'),
  (17, 'PARTICIPANT'),
  (18, 'PARTICIPANT'),
  (19, 'PARTICIPANT'),
  (20, 'PARTICIPANT'),
  (21, 'PARTICIPANT'),
  (22, 'PARTICIPANT'),
  (23, 'PARTICIPANT'),
  (24, 'PARTICIPANT'),
  (25, 'PARTICIPANT'),
  (26, 'PARTICIPANT'),
  (27, 'PARTICIPANT');


--------------------------

INSERT INTO USER_LIKE(app_user_id, liked_user_id) VALUES
  (17, 7),
  (19, 4),
  (17, 20),
  (25, 1),
  (5, 8),
  (3, 24),
  (6, 7),
  (5, 18),
  (11, 22),
  (25, 26),
  (26, 17),
  (8, 15),
  (4, 10),
  (27, 1),
  (12, 11),
  (7, 22),
  (16, 19),
  (15, 14),
  (13, 10),
  (26, 18),
  (1, 12),
  (6, 13),
  (24, 21),
  (21, 24),
  (1, 21),
  (7, 21),
  (3, 11),
  (18, 26),
  (7, 2),
  (11, 10),
  (24, 18),
  (15, 23),
  (12, 13),
  (20, 21),
  (18, 5),
  (18, 16),
  (17, 24),
  (27, 5),
  (1, 10),
  (6, 4),
  (15, 10),
  (13, 6),
  (20, 10),
  (1, 19),
  (13, 19),
  (2, 24),
  (9, 13),
  (4, 6),
  (24, 25),
  (6, 20),
  (12, 4),
  (10, 20),
  (7, 17),
  (10, 15),
  (4, 22),
  (16, 14),
  (5, 23),
  (20, 17),
  (11, 19),
  (18, 1),
  (22, 20),
  (21, 20),
  (9, 24),
  (24, 19),
  (13, 2),
  (1, 23),
  (2, 20),
  (23, 20),
  (1, 9),
  (8, 7),
  (23, 1),
  (3, 26),
  (6, 5),
  (14, 16),
  (19, 16),
  (10, 16),
  (16, 8),
  (14, 7),
  (19, 5),
  (25, 13),
  (13, 18),
  (22, 1),
  (2, 4),
  (8, 4),
  (23, 4),
  (10, 11),
  (4, 18),
  (5, 19),
  (19, 15),
  (15, 8),
  (13, 21),
  (2, 26),
  (1, 2),
  (9, 15),
  (23, 11),
  (8, 20),
  (4, 23),
  (24, 23),
  (7, 23),
  (24, 10),
  (2, 16),
  (26, 21),
  (23, 16),
  (3, 13),
  (18, 24),
  (27, 13),
  (14, 20),
  (15, 17),
  (14, 11),
  (1, 22),
  (15, 2),
  (26, 22),
  (27, 7),
  (11, 6);

--------------------------
